version: '3.9'

services:
  # ----------------------------------------------------------
  # 1) PostgreSQL Database Service
  # ----------------------------------------------------------
  postgres:
    image: postgres:15
    container_name: fireworks_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ----------------------------------------------------------
  # 2) FastAPI Backend
  # ----------------------------------------------------------
  backend:
    build:
      context: ../backend
    container_name: fireworks_backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  # ----------------------------------------------------------
  # 3) Next.js Frontend
  # ----------------------------------------------------------
  frontend:
    build:
      context: ../frontend/fireworks-demo
    container_name: fireworks_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  # ----------------------------------------------------------
  # 4) Airflow Webserver
  #
  #    - Uses your Airflow Dockerfile in ../airflow
  #    - Connects to Postgres with LocalExecutor
  # ----------------------------------------------------------
  airflow-webserver:
    build:
      context: ../airflow
    container_name: fireworks_airflow_webserver
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__WEBSERVER__WORKERS=1
      # Optionally set a Fernet key from .env:
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
    volumes:
      - airflow_data:/opt/airflow
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["webserver"]  # Start Airflow webserver

  # ----------------------------------------------------------
  # 5) Airflow Scheduler
  #
  #    - Same Airflow image, same Postgres config
  #    - Runs the scheduler
  # ----------------------------------------------------------
  airflow-scheduler:
    build:
      context: ../airflow
    container_name: fireworks_airflow_scheduler
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
    volumes:
      - airflow_data:/opt/airflow
    depends_on:
      - airflow-webserver
    command: ["scheduler"]  # Start Airflow scheduler

volumes:
  postgres_data:
  airflow_data:

